import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Contact from "@/components/Contact";
import localFont from "next/font/local";
import SpeakerCard from "@/components/SpeakerCard";
import { Toaster } from "@/components/ui/sonner";

const eUkraine = localFont({
  src: [
    {
      path: "./fonts/e-Ukraine-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/e-Ukraine-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/e-Ukraine-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-e-ukraine",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={`${eUkraine.variable} ${geistMono.variable} min-h-full flex flex-col font-sans`}
      >
        <Contact />
        <Header />
        <SpeakerCard />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
