/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SpeakerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "speaker";
};

export type Seminar = {
  _id: string;
  _type: "seminar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: "small" | "medium" | "full";
        align?: "left" | "center" | "right";
        _type: "image";
        _key: string;
      }
  >;
  eventDates: Array<string>;
  location?: string;
  status: "upcoming" | "past" | "recording";
  type?: Array<string>;
  category?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  speakers?: Array<
    {
      _key: string;
    } & SpeakerReference
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Speaker = {
  _id: string;
  _type: "speaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  title?: Array<string>;
  bio?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: "small" | "medium" | "full";
        align?: "left" | "center" | "right";
        _type: "image";
        _key: string;
      }
  >;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Category
  | Slug
  | SanityImageAssetReference
  | CategoryReference
  | SpeakerReference
  | Seminar
  | SanityImageCrop
  | SanityImageHotspot
  | Speaker
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: features/seminars/queries/getCategoriesQuery.ts
// Variable: getCategoriesQuery
// Query: *[      _type == "category" &&      count(*[        _type == "seminar" &&         status in ["upcoming", "recording"] &&        references(^._id)      ]) > 0    ] {      _id,      title,      "slug": slug.current    }
export type GetCategoriesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string | null;
}>;

// Source: features/seminars/queries/getSeminarBySlug.ts
// Variable: getSeminarBySlug
// Query: *[_type == "seminar" && slug.current == $slug][0]{    _id,  title,  "slug": slug.current,  description,  eventDates,  price,  location,  status,  type,  category,  "image": image.asset->url,  speakers[]->{    _id,    name,    slug,    title,    company,    bio,    photo  }  }
export type GetSeminarBySlugResult = {
  _id: string;
  title: string;
  slug: string;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: "full" | "medium" | "small";
        align?: "center" | "left" | "right";
        _type: "image";
        _key: string;
      }
  > | null;
  eventDates: Array<string>;
  price: null;
  location: string | null;
  status: "past" | "recording" | "upcoming";
  type: Array<string> | null;
  category: Array<
    {
      _key: string;
    } & CategoryReference
  > | null;
  image: string | null;
  speakers: Array<{
    _id: string;
    name: string;
    slug: Slug;
    title: Array<string> | null;
    company: null;
    bio: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          size?: "full" | "medium" | "small";
          align?: "center" | "left" | "right";
          _type: "image";
          _key: string;
        }
    > | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
} | null;

// Source: features/seminars/queries/getSeminarsQuery.ts
// Variable: getSeminarsQuery
// Query: {    "items": *[      _type == "seminar"      && status in ["upcoming", "recording"]      && (!defined($category) || count((category[]->slug.current)[@ in $category]) > 0)    ] | order(eventDates[0] desc) [$start...$end] {        _id,  title,  "slug": slug.current,  description,  eventDates,  price,  location,  status,  type,  category,  "image": image.asset->url,  speakers[]->{    _id,    name,    slug,    title,    company,    bio,    photo  }    },    "total": count(*[      _type == "seminar"      && status in ["upcoming", "recording"]      && (!defined($category) || count((category[]->slug.current)[@ in $category]) > 0)    ])  }
export type GetSeminarsQueryResult = {
  items: Array<{
    _id: string;
    title: string;
    slug: string;
    description: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          size?: "full" | "medium" | "small";
          align?: "center" | "left" | "right";
          _type: "image";
          _key: string;
        }
    > | null;
    eventDates: Array<string>;
    price: null;
    location: string | null;
    status: "past" | "recording" | "upcoming";
    type: Array<string> | null;
    category: Array<
      {
        _key: string;
      } & CategoryReference
    > | null;
    image: string | null;
    speakers: Array<{
      _id: string;
      name: string;
      slug: Slug;
      title: Array<string> | null;
      company: null;
      bio: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "blockquote" | "h2" | "h3" | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              openInNewTab?: boolean;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
            size?: "full" | "medium" | "small";
            align?: "center" | "left" | "right";
            _type: "image";
            _key: string;
          }
      > | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  }>;
  total: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n   *[\n      _type == "category" &&\n      count(*[\n        _type == "seminar" &&\n         status in ["upcoming", "recording"] &&\n        references(^._id)\n      ]) > 0\n    ] {\n      _id,\n      title,\n      "slug": slug.current\n    }\n': GetCategoriesQueryResult;
    '*[_type == "seminar" && slug.current == $slug][0]{\n  \n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  eventDates,\n  price,\n  location,\n  status,\n  type,\n  category,\n  "image": image.asset->url,\n  speakers[]->{\n    _id,\n    name,\n    slug,\n    title,\n    company,\n    bio,\n    photo\n  }\n\n  }\n': GetSeminarBySlugResult;
    '\n  {\n    "items": *[\n      _type == "seminar"\n      && status in ["upcoming", "recording"]\n      && (!defined($category) || count((category[]->slug.current)[@ in $category]) > 0)\n    ] | order(eventDates[0] desc) [$start...$end] {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  eventDates,\n  price,\n  location,\n  status,\n  type,\n  category,\n  "image": image.asset->url,\n  speakers[]->{\n    _id,\n    name,\n    slug,\n    title,\n    company,\n    bio,\n    photo\n  }\n\n    },\n    "total": count(*[\n      _type == "seminar"\n      && status in ["upcoming", "recording"]\n      && (!defined($category) || count((category[]->slug.current)[@ in $category]) > 0)\n    ])\n  }\n': GetSeminarsQueryResult;
  }
}
